### PR TITLE
I'm trying to add a new set of interfaces

### PR DESCRIPTION
**Pull request by ykai55**
# New Architecture

I created a new architecture to simplify the connections between platform, strategy and referee. The core idea is let strategy and referee be services server for platform. The strategy service offers robots' command and the referee offer foul determinations. And they are all requested by platform so there is no connection between referee and strategy. In other words, services are 'static' and drived by platform. They just provide some data according platform's input.

The new architecture like this:

```
+-------------+         +------------------+
|             |         |                  |
|          +--------------->               |
|             |         |     strategy     |
|          <---------------+  service      |
|             |         |                  |
|             |         +------------------+
|  platform   |
|             |         +------------------+
|             |         |                  |
|          +--------------->               |
|             |         |     referee      |
|          <---------------+  service      |
|             |         |                  |
+-------------+         +------------------+

```

# File Description

All file is in new folder.

- new/API.proto

Including RPC calls' definitions of referee service and strategy service.

- new/base.proto

Including base structures like `Environment`.

- new/command.proto

Including structures required by strategy service.

- new/referee.proto

Including structures required by referee service.

### CODE REVIEW

**Comment by mahi97** [comment]
I believe the last architecture that we decided is pretty simple and more reliable.
Since connecting agents and referee separately to the platform have to need more effort for syncing communication and decide how to apply agent request based on referee make platform logic more complicated.

It was okay if the response to each client like referee or strategy doesn't need to be sync and doesn't have an effect on each other.

For example, we can check inside the referee that position that requested by clients is okay or not according to the rules, but now we should receive them once in platform pass is to referee and wait for referee response and the pass it to agents.
OR add this logic to the platform itself that makes the platform way too complicated since half of the rules are handled in referee and half in the platform.

**Comment by ykai55** [comment]
Let's see the old one:

```
+---------------------------------------------------------+
|platform                                                 |
|              path1                  path2               |
|     ^          +                      +           ^     |
|     |          |                      |           |     |
+---------------------------------------------------------+
      |          |                      |           |
      |          |                      |      (corrected)
   command   environment          environment   placement
      |          |                      |           |
+----------------------+           +----------------------+
|     |          |     |           |    |           |     |
|     +----------+     |           |    |           |     |
|                      | gamestate |    |           |     |
|                   <-------------------+           |     |
|                      |           |                |     |
|                      | placement |                |     |
|              path3+-------------------------------+     |
|clients               |           |               referee|
+----------------------+           +----------------------+
```

### We should not have a unsynchronized communication.

The platform is for strategy developers and it's our's duty to ensure "every frame strategies received is reliable". But if we don't want to synchronize messages, the effectiveness of data cannot be ensured, just like we discussed before in discord. We need every frame is under control.

That is a problem and we should solve it.

For example, if we use the unsynchroized one, the platform don't exactly know when a foul caused. So if a foul happened, the path1 in the graph could run once even more. What if take a goal in this(these) frame(s)? The platform don't know anything and just record the score as valid.

### About complexity

Perhaps it is not so complicated. If we could have a self-controlled run model, it was solved. Compared to time-driven platform, maybe we just need let it be a event-driven, timeout and data received are both events but they have different priorities.

**Comment by mahi97** [comment]
There is no path 1 in the architecture. 
The environment and commands will also be handled by the referee.

**Comment by mahi97** [comment]
The platform should run time driven. Otherwise, it's not realistic nor reliable.
But the referee and strategy run event-driven that can be sync and simple.

But If one strategy can not run in the dedicated time that team miss the chance to send a command to their robots for that loop and other parts will not be affected.

**Comment by ykai55** [comment]
Sorry for my fault. Where can i see the architecture using? Does it treat referee as center?

In addition, the `dWorldStep` function has a step size argument, so perhaps we can control the time via passing a same value. Reality we are talking is for simulation time, not for us to look real. That is to say, in a certain case, the effect of one beat is fixed.

**Comment by mahi97** [comment]
Yes the referee is the center as we discussed in discord also.
I will send an email in weekend for the final version of message and architecture.

I want to try gRPC for the communication so it takes a little more time.

**Pull request closed without merging**
